# Default values for servicegateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/mittwald/servicegateway
  #tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

servicegateway:
  config:
    content: {}
    mountPath: "/srv/servicegateway/config"

service:
  type: ClusterIP
  port: 80

gateway:
  port: 8080
  debug: false

admin:
  port: 8081
  addr: 127.0.0.1

monitoring:
  port: 8082
  addr: 0.0.0.0

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

ingresses: {}
#ingresses:
#  youringressname:
#    enabled: true
#    annotations:
#      kubernetes.io/ingress.class: nginx
#      kubernetes.io/tls-acme: "true"
#      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
#    hosts:
#      - host: chart-example.local
#        paths: ["/"]
#    tls:
#      - secretName: chart-example-tls
#        hosts:
#          - chart-example.local

probes:
  livenessProbe:
    httpGet:
      path: /status
      port: monitoring
  readinessProbe:
    httpGet:
      path: /status
      port: monitoring

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

additionalLabels: {}
  # foo.bar/mylabel: true
  # bar.foo/anotherlabel: true

additionalArgs: []
  # - -foobar /srv/foo
# - -barfoo /foo/srv

additionalConfigmapData: {}
  # foo: bar
  # foobar: |
#  multilinebar

additionalVolumeMounts: []
  # - name: config-volume
#   mountPath: test123

additionalVolumes: []
  # - name: foobar
#   configmap: barfoo

additionalEnv: []
  # - name: fooname
#   value: foovalue

nodeSelector: {}

tolerations: []

affinity: {}