apiVersion: v1
kind: Service
metadata:
  name: {{ include "servicegateway.fullname" . }}
  labels:
{{ include "servicegateway.labels" . | indent 4 }}
{{- if .Values.additionalLabels }}
{{ toYaml .Values.additionalLabels | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.gateway.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "servicegateway.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}